### ISSUE TITLE
Ignoring testdata and .folders

### ISSUE THREAD

**Issue by svperfecta** [go-playground/overalls#14]
As far as I know, the go tools ignore two special folders: `testdata` and anything that begins `.`.  Should we do the same here?

**Comment by deankarn** [comment]
Hey @genexp,

not a bad idea, however, what if there were code in a hidden directory that you did want to test?

I think leaving it to the user to identify which folders to ignore is preferable:
```overalls -project=github.com/go-playground/overalls -covermode=count -debug -ignore=.git,testdata```

thoughts?

**Comment by svperfecta** [comment]
Sure sure, all good.  Just wondered, it bit me in our CI today when tests passed locally but not on the server.  Locally we use test, but we use overalls on CI to generate coverage reports.  Lovely software by the way :)

**Comment by deankarn** [comment]
Thanks @genexp glad it's helping others as well 😄 

if a bunch of people request this I will definitely make that change, but because it could be a breaking change, if someone is running this on hidden folders now, I'll hold off for now.
