### ISSUE TITLE
Support symbolic links

### ISSUE THREAD

**Issue by F21** [go-playground/overalls#16]
As part of my CI build process, the source is mounted at `/source`. I then create a symbolic link from `/source` to `/go/src/github.com/F21/myproject`.

Unfortunately, when symbolic links are used, overalls is not able to find the tests in the project. The current solution is to copy the contents of `/source` to `/go/src/github.com/F21/myproject`, but support for  symbolic links would be super awesome!

**Comment by deankarn** [comment]
Hey @F21 

Just so I understand you have a symbolic link from `/go/src/github.com/F21/myproject` to `/source`

and when running overalls which project path are you using, `/go/src/github.com/F21/myproject`?

this sounds very much like issue #9, I will have to see if this can be done, recent changes to how overalls detects the project paths [here](https://github.com/go-playground/overalls/commit/cea5fb7be47f5f0c3a00982ca07d5f6a869fd8d4) may not make this possible.

Thanks for the suggestion 😄  and I'll look into it.

**Comment by F21** [comment]
Hey @joeybloggs 

Yes, `/go/src/github.com/F21/myproject`, is linked to `/source`. However, unlike #9, `GOPATH` is `/go`, but due to the way links are resolved, it probably sees it in the original path of `/source`.

I am running overalls like so: `overalls -project="github.com/F21/myproject" -covermode=set -ignore=.git,.glide,vendor -- -v`

It's not a blocker for me, but I hope it would be possible 😄
