### ISSUE TITLE
GPL dependency

### ISSUE THREAD

**Issue by vitalyisaev2** [go-playground/overalls#22]
I've just noticed that this project depends on "github.com/yookoala/realpath" which is licensed under GPL-like dependency. I'm not sure, but may be it's impossible to have this project licensed under MIT because of it. Anyway, thanks for a perfect library :)

**Comment by deankarn** [comment]
Thanks @vitalyisaev2 I'll look into it as soon as I can; think a pull request brought in the dependency, definitely want to keep it MIT

**Comment by deankarn** [comment]
@vitalyisaev2 I reached out to the author and he reached out to the author he based his work off of and they are both going to changing to MIT or another compatible license as soon as they find time.

so closing this :)
