### ISSUE TITLE
How to use with -args flag

### ISSUE THREAD

**Issue by erwanlbp** [go-playground/overalls#23]
Maybe I missed something in the README, but do you support the `-args` flag ? 

For example if I use the library like :
`overalls -project=github.com/erwanlbp/ionline -covermode=count -- -args -flag1 something`

The `-args` should be at the end of the go test command, because every thing after `args` is sent to the program unparsed.

What I get is something like : 
`go test -args -flag1 something -covermode=count -coverprofile=profile.coverprofile -outputdir=/path/to/package ./path/to/package`

And so it only test for the root package, which doesn't contain tests

**Comment by deankarn** [comment]
Hey @erwanlbp sorry for the late late response, this one slipped through the cracks

I definitely didn't take the `-args` flag into account, but shouldn't be hard to check if it exists and send everything after to the program; I don't know when I'll be able to get to this but will try my best.
