### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by joerocklin** [go-playground/overalls#24]
This is due to a problem with how the `realpath` package handles detecting absolute paths. https://github.com/yookoala/realpath/pull/2 has a fix.

**Comment by deankarn** [comment]
I see that it’s already been merged, and next time people do a go get will get the fix :)

 thanks @joerocklin for the heads up 👍

**Comment by joerocklin** [comment]
Indeed - everyone was awake and moving on this one :)
