### ISSUE TITLE
Support passing arguments to go test

### ISSUE THREAD

**Issue by nothingmuch** [go-playground/overalls#8]
We run our tests in CI with `-race -v`, it'd be nice if we could keep the same output, while still using overalls to actually run the tests per package and merge the coverage output.

Being able to pass arguments like `go list` takes would also be nice.

I'm happy to try and add this myself, but that would require a bit of bikeshedding (of test output, of arguments) so I wanted to bring this up for discussion first

**Comment by nothingmuch** [comment]
cf. https://gist.github.com/rjeczalik/6f01430e8554bf59b88e for interesting `go list` usage, same purpose as overalls itself

**Comment by deankarn** [comment]
Hello @nothingmuch I can definitely see how passing another command may be useful and would definitely be interested in adding that, any help would be appreciated, just really busy this month.

#### Question

Is there any reason you wouldn't `test` and `test -race` with the following command(s)
- go test ./...
- go test -race -v ./...

that's the way I do it in my CI server `./...` will recursively go through the directories. and then I run overalls after everything passes.

**Comment by nothingmuch** [comment]
For the repository I'm using overalls in right now, no, that's exactly what I'm doing.

However, I was hoping to use it on bigger projects where that would introduce a significant delay to the build process (we have a hacky solution to merge the output, but which does only one pass over the test suite, I was hoping to clean it up)

**Comment by deankarn** [comment]
@nothingmuch I see, yes I'm ok with passing other arguments if you wanted to try and add it yourself I'd be happy to accept a pull request.
